# Generated by Django 3.0.4 on 2020-04-26 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=400)),
                ('date', models.DateField()),
                ('englishReport', models.CharField(max_length=400)),
                ('valuesReport', models.CharField(max_length=400)),
                ('emotionalReport', models.CharField(max_length=400)),
                ('actionPoints', models.CharField(max_length=400)),
                ('footballSkillsReport', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default='')),
                ('numLessonsPaid', models.IntegerField()),
                ('numLessonsLeft', models.IntegerField()),
                ('packageStatus', models.CharField(choices=[('Activo', 'Activo'), ('Pendiente', 'Pendiente')], default='', max_length=20)),
                ('currentTerm', models.CharField(choices=[('Primero', 'Primero'), ('Segundo', 'Segundo'), ('Tercero', 'Tercero'), ('Cuarto', 'Cuarto')], default='', max_length=20)),
                ('nextTerm', models.CharField(choices=[('Primero', 'Primero'), ('Segundo', 'Segundo'), ('Tercero', 'Tercero'), ('Cuarto', 'Cuarto')], default='', max_length=20)),
                ('paidStatus', models.CharField(choices=[('Pagado', 'Pagado'), ('NoPagado', 'No Pagado'), ('PagadoEpayCo', 'Pagado con EpayCo')], default='', max_length=20)),
                ('category', models.CharField(choices=[('Footie', 'Footie'), ('FootiePlay', 'Footie Play')], default='', max_length=20)),
                ('campus', models.CharField(choices=[('LaColina', 'La Colina'), ('LaCalera', 'La Calera'), ('Cedritos', 'Cedritos')], max_length=20)),
                ('parent', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FootieApi.Parent')),
                ('report', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='FootieApi.Report')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='FootieApi.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('numLessons', models.IntegerField()),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='FootieApi.Student')),
            ],
        ),
    ]
